version: "3.8"
services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
        context: ./php
        dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:8.0
    volumes:
        - mysqldb:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: framework_database

volumes:
      mysqldb:
